name: LogWriter
main: com.PlayeR_SkiLL.LogWriter.LogWriter
version: 1.0
api-version: 1.12
commands:
  logwrite:
    description: Записывает сообщение в лог-файл
    usage: /logwrite <filename.yml> <message>
  logwriter:
    description: Управление плагином
    aliases: [lw]
    usage: /logwriter [reload|create <filename>]
permissions:
  logwrite.use:
    description: Разрешение на использование команды /logwrite
    default: op
  logwriter.use:
    description: Разрешение на использование команды /logwriter
    default: op
  logwriter.reload:
    description: Разрешение на перезагрузку конфигурации
    default: op
  logwriter.create:
    description: Разрешение на создание новых лог-файлов
    default: op
